git:
  depth: 3

sudo: required

services:
  - docker

before_install:
  - docker version
  - docker info
  - docker pull nanmu42/miktex-docker
  - docker image ls
  - docker volume create --name miktex

before_script:
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  nanmu42/miktex-docker mpm --admin --update
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor,]{cquthesis}%/' main.tex
  # 预先编译几遍main.tex，因为MikTeX有可能会在下宏包时报诡异的错误
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make all || true
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make all || true
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make all || true
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make all || true
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make all || true
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make all || true
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall

script:
  # 出现错误就可以停下了。
  - set -e
  # 以下所有编译都需要指定fontset=fandol，这个是MikTeX和CTeX宏包搭配时无法正常判断系统为Linux所致
  # 这违背了CI不侵入代码的初衷，既然如此，我们也可以进行多个版本/选项的测试了。
  # ===本科论文===
  # 0.最少选项基准
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 1.图录表录等分别按双语题注混编(combined)，分开编录(apart)，默认关(off)
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, bilinguallist=apart,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, bilinguallist=combined,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, bilinguallist=off,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 2.盲审模式，开启后封面姓名和致谢部分会隐藏，详情请参阅用户文档，默认关
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, blindtrail, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 3.双面打印时每章的第一页仅右页开启，默认右页开启(openright)
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, openany, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, openright, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 4.论文打印方式，默认采用auto按页数要求自动判定
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, printmode=oneside, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, printmode=twoside, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, printmode=auto, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 5.草稿模式
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, draft, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 6.仅适用本科生，使用文学类论文标题格式，默认未打开
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=bachelor, liberalformat, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # ===研究生论文===
  # 0.最少选项基准
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 1.图录表录等分别按双语题注混编(combined)，分开编录(apart)，默认关(off)
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, bilinguallist=apart,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, bilinguallist=combined,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, bilinguallist=off,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 2.盲审模式，开启后封面姓名和致谢部分会隐藏，详情请参阅用户文档，默认关
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, blindtrail, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 3.双面打印时每章的第一页仅右页开启，默认右页开启(openright)
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, openany, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, openright, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 4.论文打印方式，默认采用auto按页数要求自动判定
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, printmode=oneside, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, printmode=twoside, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, printmode=auto, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 5.草稿模式
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, draft, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 6.仅适用研究生，是(true)否(false)专业硕士，默认为否
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, proffesionalmaster=true, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=master, proffesionalmaster=false, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # ===博士生论文===
  # 0.最少选项基准
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 1.图录表录等分别按双语题注混编(combined)，分开编录(apart)，默认关(off)
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, bilinguallist=apart,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, bilinguallist=combined,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, bilinguallist=off,]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 2.盲审模式，开启后封面姓名和致谢部分会隐藏，详情请参阅用户文档，默认关
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, blindtrail, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 3.双面打印时每章的第一页仅右页开启，默认右页开启(openright)
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, openany, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, openright, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 4.论文打印方式，默认采用auto按页数要求自动判定
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, printmode=oneside, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, printmode=twoside, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, printmode=auto, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # 5.草稿模式
  - sed -i 's/\[.*\]{cquthesis}%/[fontset=fandol, type=doctor, draft, ]{cquthesis}%/' main.tex
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make thesis
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cleanall
  # ===用户文档===
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make cls
  - sed -i 's/\\RequirePackage\[UTF8,scheme=chinese\]{ctex}/\\RequirePackage[UTF8,scheme=chinese,fontset=fandol]{ctex}/' dtx-style.sty
  - docker run --rm -ti  -v miktex:/miktex/.miktex  -v $(pwd):/miktex/work  -e MIKTEX_GID=$(id -g)  -e MIKTEX_UID=$(id -u) nanmu42/miktex-docker make doc

after_failure:
  # 如果编译失败了，输出log到日志里
  - echo '===== tail from cquthesis.log =====' && tail -n 50 cquthesis.log